dist: xenial
group: edge
sudo: required
language: python
jdk:
- oraclejdk8
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
env:
- JENKINS_VERSION=stable
- JENKINS_VERSION=latest
install:
- pip install tox-travis
- python setup.py -q sdist bdist_wheel
script:
- tox
jobs:
  include:
  - stage: test
    script: tox
  - stage: release
    script: skip
    deploy:
      user: pratik025
      password:
        secure: 11f57ce33dbf88046b3a18875d5d483b8a
      on:
        repo: pycontribs/jenkinsapi
        tags: true
      provider: pypi
      distributions: sdist bdist_wheel
      skip_cleanup: true
